config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :posts do 
    resources :comments
  end

  get '/about', to: 'pages#about'

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :post, only: [:create, :edit, :update, :destroy]

  def create
    @post.comments.create(comment_params)
    redirect_to @post
  end

  def destroy
    @post.comments.find(params[:id]).destroy
    redirect_to @post
  end

  private

    def post
      @post = Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:name, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :post, only: [:edit, :update, :show, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

    def post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_title"><%= time_ago_in_words(comment.created_at) %> ago</p>
  </div>

  <% if user_signed_in? %>
    <p><%= link_to 'Delete', [comment.post, comment], data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "button" %></p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %></br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %></br>
    <%= f.text_area :body %>
  </p>
  </br>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumblrization</title>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap" %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'favicon.ico.png' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="sidebar">
      <ul>
        <li class="category"><%= link_to "Tmblrztn", root_path %></li>
        <li><%= link_to "Posts", root_path%></li>
        <li><%= link_to 'About', about_path %></li>
      </ul>
    </div	>

    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>Post Feed</p>
        <% elsif current_page?(about_path) %>
          <p>My Site</p>
        <% else %>
          <%= link_to 'Back to Post Feed', root_path %>
        <% end %>

        <div class="buttons">
          <% if user_signed_in? %>
            <button class="button"><%= link_to "Make post", new_post_path %></button>
            <button class="button"><%= link_to 'Log out', destroy_user_session_path, data: { turbo_method: :delete } %></button>
          <% else %>
            <button class="button"><%= link_to 'Login', new_user_session_path %></button>
          <% end %>
        </div>
      </div>

      <% flash.each do |name, msg| %>
			  <%= content_tag(:div, msg, class: "alert") %>
		  <% end %>

      <%= yield %>

    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "profile.jpg" %>
  </div>

  <div id="content">
    <h1>It's Mr. Stick Figure </h1>
    <p>I'm baby craft beer XOXO tofu chillwave fam, marfa microdosing echo park plaid. Chia snackwave blue bottle health goth. Pitchfork 8-bit fanny pack, four loko williamsburg blog beard yuccie. Skateboard semiotics ascot jawn lumbersexual man braid neutral milk hotel selfies flannel cupping ugh. VHS echo park austin messenger bag, pickled 90's wayfarers cred viral. Williamsburg narwhal tbh pork belly squid synth grailed kickstarter organic kitsch gochujang pickled. Gorpcore sartorial pork belly skateboard VHS meh readymade everyday carry post-ironic kogi actually.</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body%>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Fix post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="body"><%= truncate(post.body, length: 100) %></p>
    <p class="date"><%= time_ago_in_words(post.created_at) %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>Make something</h1>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago
    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_post_path(@post), class: "button" %>
      <%= link_to 'Delete', post_path(@post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "button" %>
    <% end %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
    <h3> Join dicussion: </h3>
    <%= render "comments/form" %>
  </div>
</div>